### ISSUE TITLE
TypeError: normalize is not a function

### ISSUE THREAD

**Issue by download13** [zerkalica/modern-diff#1]
I can't seem to use the library at all because of this error.

Here is an [example](https://runkit.com/download13/modern-diff-normalize-bug).

EDIT: Looks like the patcher is looking for normalize in the passed options instead of in the codec, where it should be. I edited the example with my workaround.

**Comment by zerkalica** [comment]
Sorry for delay. I fix Patch interface. Now this example works correctly.

``` js
import Immutable from 'immutable'
import {Patch, Rfc9602Codec, ImmutableAdapter} from 'modern-diff'
ImmutableAdapter.Immutable = Immutable

const patch = Patch({
    adapter: ImmutableAdapter,
    codec: Rfc9602Codec
})

patch(Immutable.fromJS({a: 1, b: 2, c: 3}), [
  { op: 'test', path: '/a', value: 1 },
  { op: 'remove', path: '/a'},
  { op: 'test', path: '/b', value: 2 },
  { op: 'replace', path: '/b', value: 22 },
  { op: 'add', path: '/d', value: 4 }
])
```

PS: Now import from single index file.
